config/routes.rb
AuthTest::Application.routes.draw do
  resources :users, only: [:new, :create, :index]
  resources :auths, only: [:new, :create, :destroy]

  root "users#new"

end

app/models/user.rb
class User < ActiveRecord::Base

  validates :email, uniqueness: true
  validates :email, presence: true, length: {minimum: 6}


  attr_accessor :password

  def authenticated? pwd
    self.hashed_password == BCrypt::Engine.hash_secret(pwd, self.salt)
  end

  before_save :hash_the_password
  private

  def hash_the_password 
    unless self.password == nil
      self.salt = BCrypt::Engine.generate_salt
      self.hashed_password = BCrypt::Engine.hash_secret self.password, self.salt
      self.password = nil
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    if session[:user_id]
      User.find(session[:user_id])
    end
  end
end

app/controllers/auths_controller.rb
class AuthsController < ApplicationController
  def new
    if current_user
      redirect_to users_path
    else
      @user = User.new
    end
  end

  def create
    if !(User.where(email: params[:user][:email]).empty?)
      user = User.find_by(email: params[:user][:email])
      if user.authenticated? params[:user][:password]
        session[:user_id] = user.id
        redirect_to users_path
      else
        redirect_to new_auth_path
        flash[:notice] = "sorry the email or password did not match"
      end
    else
      redirect_to new_auth_path
      flash[:notice] = "sorry we couldn't find that email"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to new_auth_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    if current_user
      redirect_to users_path
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params)
    # if !(User.where(email: user_params[:email]).empty?)
    #   redirect_to new_user_path
    #   flash[:notice] = "that email already exists silly"
    # else
      if @user.save
        session[:user_id] = @user.id
        redirect_to users_path
      else
        redirect_to new_user_path
        flash[:notice] = "Sorry that email already exists"
      end
    # end
  end

  def index
    @users = User.all
  end

  private 

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auths_helper.rb
module AuthsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/auths/create.html.erb
<h1>Auths#create</h1>
<p>Find me in app/views/auths/create.html.erb</p>

app/views/auths/new.html.erb
<%= flash[:notice] %> 
<h1>Sign In</h1>
<%= form_for @user, {url:"/auths", method:"post"} do |u| %>
  <div>
    <%= u.label :email %>
    <%= u.text_field :email %> 
  </div> 
  <div> 
    <%= u.label :password %>
    <%= u.password_field :password %>
  </div>
  <%= u.submit "Sign in" %> 
<% end %> 

<button><%= link_to "Sign up", new_user_path %></button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AuthTest</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<table>
  <th>Email</th>
  <th>Salted PW</th>
  <% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= user.hashed_password %></td>
  </tr>
  <% end %> 
</table>

<% if current_user %> 
  <%= button_to "Sign Out", auth_path(current_user.id), method: :delete %>
<% end %> 

app/views/users/new.html.erb
<%= flash[:notice] %> 
<h1>Sign up</h1>
<%= form_for @user do |u| %>
  <div>
    <%= u.label :email %>
    <%= u.text_field :email %> 
  </div> 
  <div> 
    <%= u.label :password %>
    <%= u.password_field :password %>
  </div>
  <%= u.submit "Sign Up" %> 
<% end %> 

<button><%= link_to "Login", new_auth_path %> </button>